language: generic
node_js:
  - "12.13"
matrix:
    include:
      - os: linux
        dist: bionic
        sudo: required

if: branch = master

before_script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi


script:
 - git stash --all
 - echo $(pwd)

after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi
  - cd Test-Suite
  - echo $(pwd)
  - git branch -a
  - git checkout remotes/origin/master
  - git status
  - bash ./generate_bc.sh
  - git status
  - git add .
  - git commit -m'update bc files'
  - git push https://Wren71:${git_key}@github.com/SVF-tools/Test-Suite.git HEAD:master